# Site settings
title: Unhinged Aspirations
email: ronaldmanganaro@gmail.com
url: https://ronaldmanganaro.github.io
description: "Software developed by a man unencumbered by the difficult path ahead and fueled by unhinged aspirations!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: UnhingedAspirations.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ronald-manganaro-58218378
  - title: facebook
    url: https://www.facebook.com/ronald.manganaro.1
  - title: github
    url: https://github.com/ronaldmanganaro

# Build settings
markdown: kramdown
permalink: pretty
auto: true
